# AI 系统服务的 url，默认不修改
url: ai:5000
# AI 系统数据库的信息。可以不修改
db:
  host: ai-db
  port: 3306
  user: root
  password: xxxxxxxxxx
  dbName: scow_ai
  debug: true
# AI 系统镜像保存 Harbor 仓库配置
harborConfig:
  # Harbor 仓库地址
  url: 10.0.0.xxx
  # Harbor 仓库中用于当前系统镜像管理的已存在的项目名称
  project: projectName
  # Harbor 仓库可登录用户的用户名
  # (建议使用上述项目的项目管理员以上权限人员，需具有 API 2.0 接口访问权限)
  user: user
  # Harbor 仓库可登录用户的登录密码
  password: password

jobMonitor:
  # grafana模版中的 dashboardId 和 dashboardName
  dashboardId: P17D2FB9C9DA87D76
  dashboardName: p17d2fb9c9da87d76
  # 作业监控中要展示的panelId, 每个字段对应一个面板 ID, 由grafana的规则决定
  panelIds:
    gpu: 4
    gpuMemory: 10
    cpu: 24
    memory: 26
    network: 46

# 选配公共的挂载目录
# publicMountPoints:
  # - /nfs/public

# 选配作业最大运行时间
# maxJobRunningTimeHours: 24

# # 文件管理（可选）
# file:
#   # 文件预览功能（必填）
#   preview:
#     # 大小限制（必填）
#     # 可接受的格式为nginx的client_max_body_size可接受的值，默认为 50m
#     limitSize: "50m"
#   # 文件编辑功能（必填）
#   edit:
#     # 文件编辑大小限制（必填）
#     # 可接受的格式为nginx的client_max_body_size可接受的值，默认为 1m
#     # 建议设置为较大值
#     limitSize: "1m"
#     # 不可编辑的文件后缀数组（可选）
#     # nonEditableFilenamePostfixes: [".exe", ".ppt"]

# 选配推理的配置
# inferConfig:
  # 选配，是否开启推理功能,默认开启
  # enabled: true
  # 推理服务代理地址，可选配置，不配置时用scow节点地址转发
  # proxyHost: www.example.com

# uiExtension:
# 消息系统UI扩展名称
# - name: notif
# 消息系统的部署Url，此url需能被外网访问
#   url: ""

# 选配：清理harbor中不存在的镜像
imageCleanup:
  # 选配，默认为开启
  enabled: true
  # 选配：默认为 0 * * * *
  cron: "0 * * * *"
