syntax = "proto3";

package notification;

enum NoticeType {
  SITE_MESSAGE = 0;
  SMS = 1;
  EMAIL = 2;
  OFFICIAL_ACCOUNT = 3;
  WE_COM = 4;
  DING_TALK = 5;
  LARK = 6;
}

enum ReadStatus {
  UNREAD = 0;
  READ = 1;
  ALL = 2;
}

enum SenderType {
  SYSTEM = 0;
  PLATFORM_ADMIN = 1;
  TENANT_ADMIN = 2;
}

enum TargetType {
  USER = 0;
  ACCOUNT = 1;
  TENANT = 2;
  FULL_SITE = 3;
}

message Template {
  string default = 1;
  string en = 2;
  string zh_cn = 3;
  string de = 4;
  string es = 5;
  string fr = 6;
  string ja = 7;
  string ko = 8;
  string pt = 9;
  string ru = 10;
}

message MessageNoticeTypeConfig {
  optional NoticeType notice_type = 1;
  optional bool enabled = 2;
  optional bool can_user_modify = 3;
}

message MessageConfig {
  string message_type = 1;
  Template title_template = 2;
  string category = 3;
  Template category_template = 4;
  repeated MessageNoticeTypeConfig notice_configs = 5;
}
