syntax = "proto3";

package notification;

import "common.proto";

message CreateMessageConfigRequest {
  optional NoticeType notice_type = 1;
  string message_type = 2;
  optional bool enabled = 3;
  optional bool can_user_modify = 4;
}

message CreateMessageConfigResponse {
}

message ModifyMessageConfigsRequest {
  repeated MessageConfig configs = 1;
}

message ModifyMessageConfigsResponse {
}

message ListMessageConfigsRequest {
}

message ListMessageConfigsResponse {
  uint32 totalCount = 1;
  repeated MessageConfig configs = 2;
}


service MessageConfigService {

  rpc CreateMessageConfig(CreateMessageConfigRequest) returns (CreateMessageConfigResponse);

  rpc ModifyMessageConfigs(ModifyMessageConfigsRequest) returns (ModifyMessageConfigsResponse);

  rpc ListMessageConfigs(ListMessageConfigsRequest) returns (ListMessageConfigsResponse);
}
