db:
  host: localhost
  port: 3306
  user: root
  password: mysqlrootpassword
  dbName: scow_quantum


backend:
  apiBase: http://localhost:8088

jupyter:
  cluster: "mock cluster"
  appId: "quantum jupyter"

device:
  recommend: ["t57", "t40", "t12"]

# 量子作业默认遵循的比特秒计价
billing:
  defaultBitSecondPrice: 0.35


# 设备布局旋转角度
# offsetDegree:
#  default: 0
#   t57: -45
#   t12: -135
