apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace.name }}
data:
  config.yaml: |
    {{- $config := deepCopy .Values.configMap.config }}
    {{- if .Values.hostPathMounts.enabled }}
    {{- $_ := set (index $config "log") "filePath" .Values.hostPathMounts.containerLogFile }}
    {{- end }}
    {{- toYaml $config | nindent 4 }}

