{{- if .Values.registrySecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registrySecret.name }}
  namespace: {{ .Values.namespace.name }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ .Values.registrySecret.server }}": {
          "username": "{{ .Values.registrySecret.username }}",
          "password": "{{ .Values.registrySecret.password }}",
          "auth": "{{- if .Values.registrySecret.auth -}}{{ .Values.registrySecret.auth }}{{- else -}}{{ printf "%s:%s" .Values.registrySecret.username .Values.registrySecret.password | b64enc }}{{- end -}}"
        }
      }
    }
{{- end }}

