apiVersion: v1
kind: Service
metadata:
  name: scow-ai-adapter
  namespace: {{ .Values.namespace.name }}
  labels:
    name: scow-ai-adapter
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
{{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
      name: {{ .Values.service.name }}
    - port: {{ .Values.monitor.port }}
      targetPort: {{ .Values.monitor.targetPort }}
{{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.monitor.nodePort }}
{{- end }}
      name: {{ .Values.monitor.name }}
  selector:
    name: scow-ai-adapter
