stages:
  - name: Code1
    reviewers: ["piccaSun"]
    fileReviewers:
      - paths: ["apps/scow-adapeters/**", "libs/protos/scheduler-adapter/**"]
        reviewers: ["283713406"]

  - name: Code2
    reviewers: ["Miracle575"]

  - name: E2E
    reviewers: ["lyl-available"]
    optional: true
