stages:
  - name: Code1
    reviewers: ["piccaSun"]

  - name: Code2
    reviewers: []
    optional: true
    fileReviewers:
      - paths: ["apps/scow-adapters/**", "libs/protos/scheduler-adapter/**"]
        reviewers: ["283713406"]

  - name: Code3
    reviewers: ["Miracle575"]

  - name: E2E
    reviewers: ["lyl-available"]
    optional: true
