/* eslint-disable */
// AUTO-GENERATED by scripts/generate-openapi-registry.mjs — do not edit manually
// Re-run after: npm run client

import { CheckAppConnectivitySchema } from "src/pages/api/app/checkConnectivity";
import { CheckShadowDeskConnectivitySchema } from "src/pages/api/app/checkShadowDeskConnectivity";
import { ConnectToAppSchema } from "src/pages/api/app/connectToApp";
import { CreateAppSessionSchema } from "src/pages/api/app/createAppSession";
import { GetAllClustersAvailableAppsSchema } from "src/pages/api/app/getAllClustersAvailableApps";
import { GetAppLastSubmissionSchema } from "src/pages/api/app/getAppLastSubmission";
import { GetAppMetadataSchema } from "src/pages/api/app/getAppMetadata";
import { GetAppSessionsSchema } from "src/pages/api/app/getAppSessions";
import { GetDynamicFormOptionsSchema } from "src/pages/api/app/getDynamicFromOptions";
import { ListAvailableAppsSchema } from "src/pages/api/app/listAvailableApps";
import { AuthCallbackSchema } from "src/pages/api/auth/callback";
import { LogoutSchema } from "src/pages/api/auth/logout";
import { ValidateTokenSchema } from "src/pages/api/auth/validateToken";
import { GetClusterInfoSchema } from "src/pages/api//cluster";
import { GetAllClusterNodesInfoSchema } from "src/pages/api/dashboard/getAllClusterNodesInfo";
import { GetAllClustersInfoSchema } from "src/pages/api/dashboard/getAllClustersInfo";
import { GetAllSummaryClustersInfoSchema } from "src/pages/api/dashboard/getAllSummaryClustersInfo";
import { GetClusterRunningInfoSchema } from "src/pages/api/dashboard/getClusterInfo";
import { GetClusterNodesInfoSchema } from "src/pages/api/dashboard/getClusterNodesInfo";
import { GetQuickEntriesSchema } from "src/pages/api/dashboard/getQuickEntries";
import { SaveQuickEntriesSchema } from "src/pages/api/dashboard/saveQuickEntries";
import { CreateDesktopSchema } from "src/pages/api/desktop/createDesktop";
import { KillDesktopSchema } from "src/pages/api/desktop/killDesktop";
import { LaunchDesktopSchema } from "src/pages/api/desktop/launchDesktop";
import { ListAvailableWmsSchema } from "src/pages/api/desktop/listAvailableWms";
import { ListDesktopsSchema } from "src/pages/api/desktop/listDesktops";
import { CheckTransferKeySchema } from "src/pages/api/file/checkTransferKey";
import { CompleteMultipartUploadSchema } from "src/pages/api/file/completeMultipartUpload";
import { CompressAndDownloadFileSchema } from "src/pages/api/file/compressAndDownload";
import { CompressFilesSchema } from "src/pages/api/file/compressFiles";
import { CopyFileItemSchema } from "src/pages/api/file/copy";
import { CreateFileSchema } from "src/pages/api/file/createFile";
import { DecompressFileSchema } from "src/pages/api/file/decompressFile";
import { DeleteDirSchema } from "src/pages/api/file/deleteDir";
import { DeleteFileSchema } from "src/pages/api/file/deleteFile";
import { DownloadFileSchema } from "src/pages/api/file/download";
import { FileExistSchema } from "src/pages/api/file/fileExist";
import { GetFileMetadataSchema } from "src/pages/api/file/getFileMetadata";
import { GetFileTypeSchema } from "src/pages/api/file/getFileType";
import { GetHomeDirectorySchema } from "src/pages/api/file/getHome";
import { InitMultipartUploadSchema } from "src/pages/api/file/initMultipartUpload";
import { ListFileSchema } from "src/pages/api/file/list";
import { ListAvailableTransferClustersSchema } from "src/pages/api/file/listAvailableTransferClusters";
import { MergeFileChunksSchema } from "src/pages/api/file/mergeFileChunks";
import { MkdirSchema } from "src/pages/api/file/mkdir";
import { MoveFileItemSchema } from "src/pages/api/file/move";
import { QueryFileTransferProgressSchema } from "src/pages/api/file/queryFileTransferProgress";
import { StartFileTransferSchema } from "src/pages/api/file/startFileTransfer";
import { TerminateFileTransferSchema } from "src/pages/api/file/terminateFileTransfer";
import { UploadFileSchema } from "src/pages/api/file/upload";
import { GetAppInitialConfigSchema } from "src/pages/api//getAppInitialConfig";
import { getClusterConfigFilesSchema } from "src/pages/api//getClusterConfigFiles";
import { GetClustersRuntimeInfoSchema } from "src/pages/api//getClustersRuntimeInfo";
import { GetIsUserEnabledRootShellSchema } from "src/pages/api//getIsUserEnabledRootShell";
import { GetUserAssociatedClusterIdsSchema } from "src/pages/api//getUserAssociatedClusterIds";
import { GetUserAssociatedClusterPartitionsSchema } from "src/pages/api//getUserAssociatedClusterPartitions";
import { GetUserAvailableClusterAppsSchema } from "src/pages/api//getUserAvalableClusterApps";
import { GetUserInfoSchema } from "src/pages/api//getUserInfo";
import { CalculateJobPriceSchema } from "src/pages/api/job/calculateJobPrice";
import { CancelJobSchema } from "src/pages/api/job/cancelJob";
import { DeleteJobTemplateSchema } from "src/pages/api/job/deleteJobTemplate";
import { GetAccountsSchema } from "src/pages/api/job/getAccounts";
import { GetAllJobsSchema } from "src/pages/api/job/getAllJobs";
import { GetAvailableAccountsAndClustersSchema } from "src/pages/api/job/getAvailableAccountsAndClusters";
import { GetAvailablePartitionsForClusterSchema } from "src/pages/api/job/getAvailablePartitionsForCluster";
import { GetJobTemplateSchema } from "src/pages/api/job/getJobTemplate";
import { GetRunningJobsSchema } from "src/pages/api/job/getRunningJobs";
import { ListJobTemplatesSchema } from "src/pages/api/job/listJobTemplates";
import { RenameJobTemplateSchema } from "src/pages/api/job/renameJobTemplate";
import { SaveAsJobTemplateSchema } from "src/pages/api/job/saveAsJobTemplate";
import { SubmitFileAsJobSchema } from "src/pages/api/job/submitFileAsJob";
import { SubmitJobSchema } from "src/pages/api/job/submitJob";
import { GetUnreadMessagesSchema } from "src/pages/api/notification/getUnreadMessages";
import { MarkMessageReadSchema } from "src/pages/api/notification/markMessageRead";
import { ChangeEmailSchema } from "src/pages/api/profile/changeEmail";
import { ChangePasswordSchema } from "src/pages/api/profile/changePassword";
import { CheckPasswordSchema } from "src/pages/api/profile/checkPassword";
import { getUserStorageInfoSchema } from "src/pages/api/storage/getUserStorageUsage";

import type { RouteEntry } from "@scow/lib-web/build/utils/typebox-to-openapi";

export const openapiRoutes: RouteEntry[] = [
  { schema: CheckAppConnectivitySchema, method: "GET", url: "/api/app/checkConnectivity" },
  { schema: CheckShadowDeskConnectivitySchema, method: "GET", url: "/api/app/checkShadowDeskConnectivity" },
  { schema: ConnectToAppSchema, method: "POST", url: "/api/app/connectToApp" },
  { schema: CreateAppSessionSchema, method: "POST", url: "/api/app/createAppSession" },
  { schema: GetAllClustersAvailableAppsSchema, method: "GET", url: "/api/app/getAllClustersAvailableApps" },
  { schema: GetAppLastSubmissionSchema, method: "GET", url: "/api/app/getAppLastSubmission" },
  { schema: GetAppMetadataSchema, method: "GET", url: "/api/app/getAppMetadata" },
  { schema: GetAppSessionsSchema, method: "GET", url: "/api/app/getAppSessions" },
  { schema: GetDynamicFormOptionsSchema, method: "GET", url: "/api/app/getDynamicFromOptions" },
  { schema: ListAvailableAppsSchema, method: "GET", url: "/api/app/listAvailableApps" },
  { schema: AuthCallbackSchema, method: "GET", url: "/api/auth/callback" },
  { schema: LogoutSchema, method: "DELETE", url: "/api/auth/logout" },
  { schema: ValidateTokenSchema, method: "GET", url: "/api/auth/validateToken" },
  { schema: GetClusterInfoSchema, method: "GET", url: "/api//cluster" },
  { schema: GetAllClusterNodesInfoSchema, method: "GET", url: "/api/dashboard/getAllClusterNodesInfo" },
  { schema: GetAllClustersInfoSchema, method: "GET", url: "/api/dashboard/getAllClustersInfo" },
  { schema: GetAllSummaryClustersInfoSchema, method: "GET", url: "/api/dashboard/getAllSummaryClustersInfo" },
  { schema: GetClusterRunningInfoSchema, method: "GET", url: "/api/dashboard/getClusterInfo" },
  { schema: GetClusterNodesInfoSchema, method: "GET", url: "/api/dashboard/getClusterNodesInfo" },
  { schema: GetQuickEntriesSchema, method: "GET", url: "/api/dashboard/getQuickEntries" },
  { schema: SaveQuickEntriesSchema, method: "POST", url: "/api/dashboard/saveQuickEntries" },
  { schema: CreateDesktopSchema, method: "POST", url: "/api/desktop/createDesktop" },
  { schema: KillDesktopSchema, method: "POST", url: "/api/desktop/killDesktop" },
  { schema: LaunchDesktopSchema, method: "POST", url: "/api/desktop/launchDesktop" },
  { schema: ListAvailableWmsSchema, method: "GET", url: "/api/desktop/listAvailableWms" },
  { schema: ListDesktopsSchema, method: "POST", url: "/api/desktop/listDesktops" },
  { schema: CheckTransferKeySchema, method: "POST", url: "/api/file/checkTransferKey" },
  { schema: CompleteMultipartUploadSchema, method: "POST", url: "/api/file/completeMultipartUpload" },
  { schema: CompressAndDownloadFileSchema, method: "GET", url: "/api/file/compressAndDownload" },
  { schema: CompressFilesSchema, method: "PATCH", url: "/api/file/compressFiles" },
  { schema: CopyFileItemSchema, method: "PATCH", url: "/api/file/copy" },
  { schema: CreateFileSchema, method: "POST", url: "/api/file/createFile" },
  { schema: DecompressFileSchema, method: "PATCH", url: "/api/file/decompressFile" },
  { schema: DeleteDirSchema, method: "DELETE", url: "/api/file/deleteDir" },
  { schema: DeleteFileSchema, method: "DELETE", url: "/api/file/deleteFile" },
  { schema: DownloadFileSchema, method: "GET", url: "/api/file/download" },
  { schema: FileExistSchema, method: "GET", url: "/api/file/fileExist" },
  { schema: GetFileMetadataSchema, method: "GET", url: "/api/file/getFileMetadata" },
  { schema: GetFileTypeSchema, method: "GET", url: "/api/file/getFileType" },
  { schema: GetHomeDirectorySchema, method: "GET", url: "/api/file/getHome" },
  { schema: InitMultipartUploadSchema, method: "POST", url: "/api/file/initMultipartUpload" },
  { schema: ListFileSchema, method: "GET", url: "/api/file/list" },
  { schema: ListAvailableTransferClustersSchema, method: "GET", url: "/api/file/listAvailableTransferClusters" },
  { schema: MergeFileChunksSchema, method: "POST", url: "/api/file/mergeFileChunks" },
  { schema: MkdirSchema, method: "POST", url: "/api/file/mkdir" },
  { schema: MoveFileItemSchema, method: "PATCH", url: "/api/file/move" },
  { schema: QueryFileTransferProgressSchema, method: "GET", url: "/api/file/queryFileTransferProgress" },
  { schema: StartFileTransferSchema, method: "POST", url: "/api/file/startFileTransfer" },
  { schema: TerminateFileTransferSchema, method: "POST", url: "/api/file/terminateFileTransfer" },
  { schema: UploadFileSchema, method: "POST", url: "/api/file/upload" },
  { schema: GetAppInitialConfigSchema, method: "GET", url: "/api//getAppInitialConfig" },
  { schema: getClusterConfigFilesSchema, method: "GET", url: "/api//getClusterConfigFiles" },
  { schema: GetClustersRuntimeInfoSchema, method: "GET", url: "/api//getClustersRuntimeInfo" },
  { schema: GetIsUserEnabledRootShellSchema, method: "GET", url: "/api//getIsUserEnabledRootShell" },
  { schema: GetUserAssociatedClusterIdsSchema, method: "GET", url: "/api//getUserAssociatedClusterIds" },
  { schema: GetUserAssociatedClusterPartitionsSchema, method: "GET", url: "/api//getUserAssociatedClusterPartitions" },
  { schema: GetUserAvailableClusterAppsSchema, method: "GET", url: "/api//getUserAvalableClusterApps" },
  { schema: GetUserInfoSchema, method: "GET", url: "/api//getUserInfo" },
  { schema: CalculateJobPriceSchema, method: "GET", url: "/api/job/calculateJobPrice" },
  { schema: CancelJobSchema, method: "DELETE", url: "/api/job/cancelJob" },
  { schema: DeleteJobTemplateSchema, method: "DELETE", url: "/api/job/deleteJobTemplate" },
  { schema: GetAccountsSchema, method: "GET", url: "/api/job/getAccounts" },
  { schema: GetAllJobsSchema, method: "GET", url: "/api/job/getAllJobs" },
  { schema: GetAvailableAccountsAndClustersSchema, method: "GET", url: "/api/job/getAvailableAccountsAndClusters" },
  { schema: GetAvailablePartitionsForClusterSchema, method: "GET", url: "/api/job/getAvailablePartitionsForCluster" },
  { schema: GetJobTemplateSchema, method: "GET", url: "/api/job/getJobTemplate" },
  { schema: GetRunningJobsSchema, method: "GET", url: "/api/job/getRunningJobs" },
  { schema: ListJobTemplatesSchema, method: "GET", url: "/api/job/listJobTemplates" },
  { schema: RenameJobTemplateSchema, method: "POST", url: "/api/job/renameJobTemplate" },
  { schema: SaveAsJobTemplateSchema, method: "POST", url: "/api/job/saveAsJobTemplate" },
  { schema: SubmitFileAsJobSchema, method: "POST", url: "/api/job/submitFileAsJob" },
  { schema: SubmitJobSchema, method: "POST", url: "/api/job/submitJob" },
  { schema: GetUnreadMessagesSchema, method: "GET", url: "/api/notification/getUnreadMessages" },
  { schema: MarkMessageReadSchema, method: "POST", url: "/api/notification/markMessageRead" },
  { schema: ChangeEmailSchema, method: "PATCH", url: "/api/profile/changeEmail" },
  { schema: ChangePasswordSchema, method: "PATCH", url: "/api/profile/changePassword" },
  { schema: CheckPasswordSchema, method: "GET", url: "/api/profile/checkPassword" },
  { schema: getUserStorageInfoSchema, method: "GET", url: "/api/storage/getUserStorageUsage" },
];
