syntax = "proto3";

package api.application;

option go_package = "scowd/protos/gen/api/application;apiv1";
import "google/protobuf/timestamp.proto";

message LoadImageRequest {
  string user_id = 1;
  string command = 2;
  string source_path = 3;
}

message LoadImageResponse {
  string image_url = 1;
}

message LoginInfo {
  string user_name = 1;
  string password = 2;
}

message PullImageRequest {
  string user_id = 1;
  string command = 2;
  string source_path = 3;
  LoginInfo login_info = 4;
}

message OutputLine {
  string stdout_content = 1;
  optional string stderr_content = 2;
}

// scowd 下增加流式响应的返回
message PullImageResponse {
  message CompletedPull {
    optional string image_url = 1;
    int32 exit_code = 2;
  }
  oneof message {
    OutputLine output = 1;
    CompletedPull completed = 2;
  }
}

message Harbor {
  string url = 1;
  string user = 2;
  string password = 3;
}
message PushImageToHarborRequest {
  string user_id = 1;
  string command = 2;
  string local_image_url = 3;
  string harbor_image_url = 4;
  Harbor harbor_info = 5;
  // 可选，执行push的节点，不传就是在scowd所在节点
  string node = 6;
}

// scowd 下增加流式响应的返回
message PushImageToHarborResponse {
  message CompletedPush {
    int32 exit_code = 1;
  }
  oneof message {
    OutputLine output = 1;
    CompletedPush completed = 2;
  }
}

message CommitContainerImageRequest {
  string user_id = 1;
  string command = 2;
  string formatted_container_id = 3;
  string node = 4;
  string image_url = 5;
}

message CommitContainerImageResponse {
}

service ImageService {
  rpc LoadImage(LoadImageRequest) returns (LoadImageResponse) {}
  rpc PullImage(PullImageRequest) returns (stream PullImageResponse) {}
  rpc PushImageToHarbor(PushImageToHarborRequest) returns (stream PushImageToHarborResponse) {}
  rpc CommitContainerImage(CommitContainerImageRequest) returns (CommitContainerImageResponse) {}
}
