syntax = "proto3";

package scow.portal;

// the runtime state of the partition
message PartitionInfo {

  enum PartitionStatus {
    NOT_AVAILABLE = 0;
    AVAILABLE = 1;
  }

  string partition_name = 1;
  uint32 node_count = 2;
  uint32 running_node_count = 3;
  uint32 idle_node_count = 4;
  uint32 not_available_node_count = 5;
  uint32 cpu_core_count =6;
  uint32 running_cpu_count = 7;
  uint32 idle_cpu_count = 8;
  uint32 not_available_cpu_count = 9;
  uint32 gpu_core_count = 10;
  uint32 running_gpu_count = 11;
  uint32 idle_gpu_count = 12;
  uint32 not_available_gpu_count = 13;
  uint32 job_count = 14;
  uint32 running_job_count = 15;
  uint32 pending_job_count = 16;
  // node utilization rate
  uint32 usage_rate_percentage = 17;
  PartitionStatus partition_status = 18;
}

message GetClusterInfoRequest {
  string cluster = 1;
}

message GetClusterInfoResponse {
  string cluster_name = 1;
  repeated PartitionInfo partitions = 2;
  // 3-17 Newly added parameters may not be returned(adapter)
  // adapter>v1.6.0 只会在getClusterNodesInfo有值的时候返回
  uint32 node_count = 3;
  uint32 running_node_count = 4;
  uint32 idle_node_count = 5;
  uint32 not_available_node_count = 6;
  uint32 cpu_core_count =7;
  uint32 running_cpu_count = 8;
  uint32 idle_cpu_count = 9;
  uint32 not_available_cpu_count = 10;
  uint32 gpu_core_count = 11;
  uint32 running_gpu_count = 12;
  uint32 idle_gpu_count = 13;
  uint32 not_available_gpu_count = 14;
  uint32 job_count = 15;
  uint32 running_job_count = 16;
  uint32 pending_job_count = 17;
}

message SummaryPartitionInfo {
  enum PartitionStatus {
    UNKNOWN = 0;
    NOT_AVAILABLE = 1;
    AVAILABLE = 2;
  }

  string partition_name = 1;
  uint32 node_count = 2;
  float node_usage = 3;
  uint32 cpu_core_count =4;
  float cpu_usage = 5;
  uint32 gpu_core_count = 6;
  float gpu_usage = 7;
  uint32 pending_job_count = 8;
  PartitionStatus partition_status = 9;
}

message GetSummaryClusterInfoRequest {
  string cluster = 1;
  repeated string account_names = 2;
}

message GetSummaryClusterInfoResponse {
  string cluster_name = 1;
  repeated SummaryPartitionInfo partitions = 2;
  // 3-17 Newly added parameters
  // only returns in version later than 1.7.0
  uint32 node_count = 3;
  uint32 running_node_count = 4;
  uint32 idle_node_count = 5;
  uint32 not_available_node_count = 6;
  uint32 cpu_core_count =7;
  uint32 running_cpu_count = 8;
  uint32 idle_cpu_count = 9;
  uint32 not_available_cpu_count = 10;
  uint32 gpu_core_count = 11;
  uint32 running_gpu_count = 12;
  uint32 idle_gpu_count = 13;
  uint32 not_available_gpu_count = 14;
  uint32 running_job_count = 15;
  uint32 pending_job_count = 16;

  float node_usage = 17;
  float cpu_usage = 18;
  float gpu_usage = 19;
}

message NodeInfo {
  // deprecated message
  // use message NodeInfo from porots/common/config instead
  option deprecated = true;
  enum NodeState {
    UNKNOWN = 0;
    IDLE = 1;
    RUNNING = 2;
    NOT_AVAILABLE = 3;
  }

  string node_name = 1;
  repeated string partitions = 2;
  NodeState state = 3;
  uint32 cpu_core_count = 4;
  uint32 alloc_cpu_core_count = 5;
  uint32 idle_cpu_core_count = 6;
  uint32 total_mem_mb = 7;
  uint32 alloc_mem_mb = 8;
  uint32 idle_mem_mb = 9;
  uint32 gpu_count = 10;
  uint32 alloc_gpu_count = 11;
  uint32 idle_gpu_count = 12;
}


message GetClusterNodesInfoRequest {
  // deprecated message
  // use message GetClusterNodesInfoRequest from porots/common/config instead
  option deprecated = true;
  // if the value of node_names = [], request all nodes info
  string cluster = 1;
  repeated string node_names = 2;
}

message GetClusterNodesInfoResponse {
  // deprecated message
  // use message GetClusterNodesInfoResponse from porots/common/config instead
  option deprecated = true;
  repeated NodeInfo nodes = 1;
}

message GetAvailableAccountsAndClustersRequest {
  string user_id = 1;
}

message AvailableAccountClusters {
  string account_name = 1;
  repeated string clusters = 2;
}

message GetAvailableAccountsAndClustersResponse {
  repeated AvailableAccountClusters account_clusters = 1;
}

service ConfigService {

  rpc GetClusterInfo(GetClusterInfoRequest) returns (GetClusterInfoResponse);

  rpc GetSummaryClusterInfo(GetSummaryClusterInfoRequest) returns (GetSummaryClusterInfoResponse);

  /**
   * Depracated Notice
   * This API funcition GetClusterNodesInfo has been deprecated.
   * Use the new COMMON API function getClusterNodesInfo from ConfigServiceService from protos/common/config instead.
   */
  rpc GetClusterNodesInfo(GetClusterNodesInfoRequest) returns (GetClusterNodesInfoResponse) {
    option deprecated = true;
  };

  rpc GetAvailableAccountsAndClusters(GetAvailableAccountsAndClustersRequest) returns (GetAvailableAccountsAndClustersResponse);
}
