FROM ccrepo.pku.edu.cn/dockerhub/library/node:22-alpine AS base

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

RUN apk update && apk add libc6-compat python3 make gcc g++ git

RUN npm i -g corepack@0.31.0

RUN corepack enable

WORKDIR /app

COPY package.json .
COPY pnpm-lock.yaml .
COPY patches ./patches

ENV COREPACK_NPM_REGISTRY=https://registry.npmmirror.com

RUN pnpm config set registry https://registry.npmmirror.com

RUN pnpm fetch

FROM base AS pruner

WORKDIR /app

COPY . .
RUN pnpm i --offline --frozen-lockfile
RUN npx turbo prune --scope="@scow/docs" --docker

FROM base AS builder

WORKDIR /app
COPY --from=pruner /app/out/json/ .
RUN pnpm i --offline --frozen-lockfile

COPY --from=pruner /app/out/full/ .
COPY tsconfig.json turbo.json ./
COPY libs/tsconfig.json ./libs/
COPY protos ./protos

RUN pnpm build

FROM ccrepo.pku.edu.cn/dockerhub/library/nginx:alpine AS runner

COPY docs/nginx.conf /etc/nginx/templates/default.conf.template
COPY --from=builder --chown=nginx:nginx /app/docs/build /etc/nginx/html/

ARG BASE_PATH="/"
ENV BASE_PATH=${BASE_PATH}

EXPOSE 80
