syntax = "proto3";

package scow.server;

import "google/protobuf/timestamp.proto";

enum ChangeStorageQuotaMode {
  INCREASE = 0;
  DECREASE = 1;
  SET = 2;
}

message PlatFormAdminInfo {
  string user_id = 1;
  string user_name = 2;
}

message PlatFormFinancialStaffInfo {
  string user_id = 1;
  string user_name = 2;
}

message ChangeStorageQuotaRequest {
  string user_id = 1;
  string cluster = 2;
  ChangeStorageQuotaMode mode = 3;
  uint64 value = 4;
}

// INVALID_ARGUMENT: change value is not valid.
// NOT_FOUND: user_id or cluster is not found
message ChangeStorageQuotaResponse {
  uint64 current_quota = 1;
}

message QueryStorageQuotaRequest {
  string user_id = 1;
  string cluster = 2;
}

// NOT_FOUND: cluster or userId is not found.
message QueryStorageQuotaResponse {
  uint64 current_quota = 1;
}

message ImportUsersData {
  message AccountInfo {
    string account_name = 1;
    repeated UserInAccount users = 2;
    // owner is undefined while account has existed
    optional string owner = 3;
    bool blocked = 4;
  }

  repeated AccountInfo accounts = 1;
}

message ImportUsersRequest {
  ImportUsersData data = 1;
  bool whitelist = 2;
}

// INVAD_ARGUMENT: the data format is not acceptable
message ImportUsersResponse {
  uint32 user_count = 1;
  uint32 account_count = 2;
  uint32 users_without_name = 3;
}

message UserInAccount {
  string user_id = 1;
  string user_name = 2;
  bool blocked = 3;
}

message ClusterAccountInfo {
  enum ImportStatus {
    EXISTING = 0;
    NOT_EXISTING = 1;
    HAS_NEW_USERS = 2;
  }
  string account_name = 1;
  repeated UserInAccount users = 2;
  optional string owner = 3;
  ImportStatus import_status = 4;
  bool blocked = 5;
}

message GetClusterUsersRequest {
  string cluster = 1;
}

message GetClusterUsersResponse {
  repeated ClusterAccountInfo accounts = 1;
}

message GetFetchInfoRequest {
}

message GetFetchInfoResponse {
  bool fetch_started = 1;
  string schedule = 2;
  optional google.protobuf.Timestamp last_fetch_time = 3;
}

message SetFetchStateRequest {
  bool started = 1;
}
message SetFetchStateResponse {
}

message FetchJobsRequest {
}
message FetchJobsResponse {
  uint32 new_jobs_count = 1;
}

message GetSyncBlockStatusInfoRequest {
}
message GetSyncBlockStatusInfoResponse {
  bool sync_started = 1;
  string schedule = 2;
  optional google.protobuf.Timestamp last_sync_time = 3;
}

message SetSyncBlockStatusStateRequest {
  bool started = 1;
}
message SetSyncBlockStatusStateResponse {
}

message BlockedFailedUserAccount {
  option deprecated = true;
  string account_name = 1;
  string user_id= 2;
}
message SyncBlockStatusRequest{
  option deprecated = true;
}
message SyncBlockStatusResponse{
  option deprecated = true;
  repeated string blocked_failed_accounts = 1;
  repeated BlockedFailedUserAccount blocked_failed_user_accounts = 2;
  repeated string unblocked_failed_accounts = 3;
}

message UpdateBlockStatusRequest{
}
message UpdateBlockStatusResponse{
}

message GetAdminInfoRequest {
}

message GetAdminInfoResponse {
  repeated PlatFormAdminInfo platform_admins = 1;
  uint64 tenant_count = 2;
  uint64 account_count = 3;
  uint64 user_count = 4;
  repeated PlatFormFinancialStaffInfo platform_financial_staff = 5;
}

message GetStatisticInfoRequest {
  google.protobuf.Timestamp start_time = 1;
  google.protobuf.Timestamp end_time = 2;
}

message GetStatisticInfoResponse {
  uint64 total_user = 1;
  uint64 total_account = 2;
  uint64 total_tenant = 3;
  uint64 new_user = 4;
  uint64 new_account = 5;
  uint64 new_tenant = 6;
  google.protobuf.Timestamp refresh_time = 7;
}

message StartAccountUserSynchronizationRequest {
  optional string operator_id = 1;
  optional uint32 max_sync_duration_minutes = 2;
}

message StartAccountUserSynchronizationResponse {
  string session_id = 1;
}

message ListAccountUserSynchronizationsRequest {
  optional uint32 page = 1;
  optional uint32 page_size = 2;
}

message ListAccountUserSynchronizationsResponse {
  enum SyncStatus {
    STATUS_UNKNOWN = 0;
    RUNNING = 1;
    COMPLETED = 2;
    UNEXECUTED = 3;
  }
  enum SyncResult {
    RESULT_UNKNOWN = 0;
    SUCCESS = 1;
    FAILED = 2;
  }

  enum SyncExceptionType {
    EXCEPTION_UNKNOWN = 0;
    NO_EXCEPTION = 1;
    CHUNK_FAILED = 2;
    ASSIGNED_PARTITIONS_FETCH_FAILED = 3;
    CLUSTER_UNEXECUTED = 4;
    // 超过管理员指定最长同步处理时间
    MAX_EXECUTION_TIME_EXCEEDED = 5;
  }

  message ExceptionDetail {
    SyncExceptionType exception_type = 1;
    string exception_message = 2;
  }

  message AccountOperationResult {
    string account_name = 1;
    bool success = 2;
    optional string failure_message = 3;
  }

  message UserAccountOperationResult {
    string account_name = 1;
    string user_id = 2;
    bool success = 3;
    optional string failure_message = 4;
  }

  message UserOperationResult {
    string user_id = 1;
    bool success = 2;
    optional string failure_message = 3;
  }

  message CreateAccountOperation {
    repeated AccountOperationResult results = 1;
  }
  message BlockAccountOperation {
    repeated AccountOperationResult results = 1;
  }
  message UnblockAccountOperation {
    repeated AccountOperationResult results = 1;
  }
  message AddUserToAccountOperation {
    repeated UserAccountOperationResult results = 1;
  }
  message BlockUserInAccountOperation {
    repeated UserAccountOperationResult results = 1;
  }
  message RemoveUserFromAccountOperation {
    repeated UserAccountOperationResult results = 1;
  }
  // 暂未使用
  message UnblockUserInAccountOperation {
    repeated UserAccountOperationResult results = 1;
  }
  // 暂未使用
  message DeleteAccountOperation {
    repeated AccountOperationResult results = 1;
  }
  // 暂未使用
  message DeleteUserOperation {
    repeated UserOperationResult results = 1;
  }

  message SyncDetailsSummary {
    optional CreateAccountOperation create_account = 1;
    optional BlockAccountOperation block_account = 2;
    optional UnblockAccountOperation unblock_account = 3;
    optional AddUserToAccountOperation add_user_to_account = 4;
    optional BlockUserInAccountOperation block_user_in_account = 5;
    optional RemoveUserFromAccountOperation remove_user_from_account = 6;
    // 暂未使用
    optional UnblockUserInAccountOperation unblock_user_in_account = 7;
    // 暂未使用
    optional DeleteAccountOperation delete_account = 8;
    // 暂未使用
    optional DeleteUserOperation delete_user = 9;
  }

  message ClusterTotalSyncResult {
    string cluster_id = 1;
    SyncStatus cluster_sync_status = 2;
    optional SyncResult cluster_sync_result = 3;
    uint32 executed_chunk_count = 4;
    bool is_all_chunk_executed = 5;
    uint32 completed_total_sync_count = 6;
    uint32 successful_total_sync_count = 7;
    repeated ExceptionDetail cluster_sync_exceptions = 8;
    optional SyncDetailsSummary cluster_sync_details = 9;
  }

  message ClusterSyncResults {
    repeated ClusterTotalSyncResult results = 1;
  }

  message SyncSessionInfo {
    string session_id = 1;
    google.protobuf.Timestamp start_time = 2;
    optional google.protobuf.Timestamp end_time = 3;
    optional string operator_id = 4;
    optional string operator_name = 5;
    SyncStatus session_sync_status = 6;
    optional SyncResult session_sync_result = 7;
    optional ClusterSyncResults session_sync_details = 8;
  }

  repeated SyncSessionInfo sync_session_infos = 1;
  uint64 total_count = 2;
  optional uint32 max_sync_duration_minutes = 3;
}

message CheckAccountUserSynchronizationRunningRequest {
}

message CheckAccountUserSynchronizationRunningResponse {
  bool is_running = 1;
}

service AdminService {
  rpc ChangeStorageQuota(ChangeStorageQuotaRequest)
      returns (ChangeStorageQuotaResponse);
  rpc QueryStorageQuota(QueryStorageQuotaRequest)
      returns (QueryStorageQuotaResponse);
  rpc ImportUsers(ImportUsersRequest) returns (ImportUsersResponse);
  rpc GetClusterUsers(GetClusterUsersRequest) returns (GetClusterUsersResponse);
  rpc GetFetchInfo(GetFetchInfoRequest) returns (GetFetchInfoResponse);
  rpc SetFetchState(SetFetchStateRequest) returns (SetFetchStateResponse);
  rpc FetchJobs(FetchJobsRequest) returns (FetchJobsResponse);

  /*
   * Synchronize block status of account and account user to the backing scheduler
   * If the synchronization is already running when the API is called, it throws ALREADY_EXISTS
   */
  rpc UpdateBlockStatus(UpdateBlockStatusRequest)
    returns (UpdateBlockStatusResponse);
  rpc GetAdminInfo(GetAdminInfoRequest) returns (GetAdminInfoResponse) {
    option deprecated = true;
  };

  rpc GetStatisticInfo(GetStatisticInfoRequest)
    returns (GetStatisticInfoResponse);
  rpc GetSyncBlockStatusInfo(GetSyncBlockStatusInfoRequest) returns (GetSyncBlockStatusInfoResponse);
  rpc SetSyncBlockStatusState(SetSyncBlockStatusStateRequest) returns (SetSyncBlockStatusStateResponse);

  /** Deprecated
      for using new api interface of StartAccountUserSynchronization.
      In addition to executing the blocked status synchronization,
      it also synchronizes account and account-associated user data to the cluster.
   */
  rpc SyncBlockStatus(SyncBlockStatusRequest) returns (SyncBlockStatusResponse) {
    option deprecated = true;
  };

  rpc StartAccountUserSynchronization(StartAccountUserSynchronizationRequest) returns (
    StartAccountUserSynchronizationResponse
  );

  rpc ListAccountUserSynchronizations(ListAccountUserSynchronizationsRequest) returns (
    ListAccountUserSynchronizationsResponse
  );

  rpc CheckAccountUserSynchronizationRunning(CheckAccountUserSynchronizationRunningRequest) returns (
    CheckAccountUserSynchronizationRunningResponse
  );
}
