syntax = "proto3";

package scow.server;

import "common/money.proto";

// if both exist user_id and user_ids, user_ids will overwrite user_id
// NOT_FOUND: the user is not in the account
message SetJobChargeLimitRequest {
  string tenant_name = 1;
  string account_name = 2;
  optional string user_id = 3;
  common.Money limit = 4;
  repeated string user_ids = 5;
}

message JobChargeLimitResult{
  bool success = 1;
  string user_id = 2;
}

message SetJobChargeLimitResponse {
  bool success = 1;
  repeated JobChargeLimitResult results = 2;
}

// if both exist user_id and user_ids, user_ids will overwrite user_id
// NOT_FOUND: the user is not in the account || the user doesn't have a charge
message CancelJobChargeLimitRequest {
  string tenant_name = 1;
  string account_name = 2;
  optional string user_id = 3;
  optional bool unblock = 4;
  repeated string user_ids = 5;
}

message CancelJobChargeLimitResponse {
  bool success = 1;
  repeated JobChargeLimitResult results = 2;
}

service JobChargeLimitService {

  rpc SetJobChargeLimit(SetJobChargeLimitRequest)
      returns (SetJobChargeLimitResponse);

  rpc CancelJobChargeLimit(CancelJobChargeLimitRequest)
      returns (CancelJobChargeLimitResponse);
}
