import { router } from "src/server/trpc/def";

import {
  checkAppConnectivity,
  checkDevHostAppConnectivity,
  connectToApp,
  connectToDevHostApp,
  createAppSession,
  getAppMetadata,
  getCreateAppParams,
  getJobDetails,
  listAllAvailableAppsFromAllClusters,
  listAppAvailableAccountsAndClusters,
  listApps,
  listAppSessions,
  listAvailableApps,
  listTags,
  saveImage,
} from "./apps";
import { getSubmitInferenceParams, submitInferJob } from "./infer";
import {
  calculateJobPrice,
  cancelJob,
  downloadPodLog,
  getJobSchedulingAndStartupLogs,
  getPodLogs,
  getPodMonitorInfo,
  getPodsByJobId,
  getSubmitTrainParams,
  trainJob,
} from "./jobs";
import { deleteTemplate, listTemplates, renameTemplate, saveTemplate } from "./templates";

export const jobsRouter = router({
  listAllAvailableAppsFromAllClusters,
  listAvailableApps,
  getAppMetadata,
  createAppSession,
  listAppSessions,
  checkAppConnectivity,
  checkDevHostAppConnectivity,
  getCreateAppParams,
  connectToApp,
  connectToDevHostApp,
  listApps,
  listTags,
  cancelJob,
  saveImage,
  trainJob,
  getSubmitTrainParams,
  submitInferJob,
  getSubmitInferenceParams,
  getJobSchedulingAndStartupLogs,
  getPodsByJobId,
  getPodLogs,
  downloadPodLog,
  getPodMonitorInfo,
  getJobDetails,
  listAppAvailableAccountsAndClusters,
  calculateJobPrice,
  saveTemplate,
  listTemplates,
  deleteTemplate,
  renameTemplate,
});
