import { router } from "src/server/trpc/def";

import {
  checkAppConnectivity,
  checkDevHostAppConnectivity,
  connectToApp,
  connectToDevHostApp,
  createAppSession,
  getAppMetadata,
  getCreateAppParams,
  getJobDetails,
  listAllAvailableAppsFromAllClusters,
  listAppAvailableAccountsAndClusters,
  listApps,
  listAppSessions,
  listAvailableApps,
  listTags,
  saveImage,
} from "./apps";
import { getSubmitInferenceParams,submitInferJob } from "./infer";
import { calculateJobOneHourPrice,cancelJob, downloadPodLog, getJobSchedulingAndStartupLogs,
  getPodLogs, getPodMonitorInfo, getPodsByJobId, getSubmitTrainParams,
  trainJob } from "./jobs";

export const jobsRouter = router({
  listAllAvailableAppsFromAllClusters,
  listAvailableApps,
  getAppMetadata,
  createAppSession,
  listAppSessions,
  checkAppConnectivity,
  checkDevHostAppConnectivity,
  getCreateAppParams,
  connectToApp,
  connectToDevHostApp,
  listApps,
  listTags,
  cancelJob,
  saveImage,
  trainJob,
  getSubmitTrainParams,
  submitInferJob,
  getSubmitInferenceParams,
  getJobSchedulingAndStartupLogs,
  getPodsByJobId,
  getPodLogs,
  downloadPodLog,
  getPodMonitorInfo,
  getJobDetails,
  listAppAvailableAccountsAndClusters,
  calculateJobOneHourPrice,
});
