export enum AIPodReason {
  IMAGE_PULL_ERROR = "IMAGE PULL ERROR",
  MOUNT_ERROR = "MOUNT ERROR",
  RESTART_ERROR = "RESTART ERROR",
  SCHEDULING_ERROR = "SCHEDULING ERROR",
  IMAGE_PULLING = "IMAGE PULLING",
  INSUFFICIENT_RESOURCES = "INSUFFICIENT RESOURCES",
}
