# 集群显示名称
# 此文本支持国际化
displayName: hpc01Name

# 指定slurm配置
loginNodes:
  # 登录节点展示名称
  # 此文本支持国际化
  - name: login01
    # 登录节点的IP或者域名
    # 如果设置的是域名，请确认此节点的/etc/hosts中包含了域名到IP的解析信息
    address: login01
  - name: login02
    address: login02

# 适配器地址(ip地址:端口号)
adapterUrl: localhost:8972

# 门户系统代理网关节点配置
# proxyGateway:
#   # 带协议，不要以/结尾
#   url: http://10.2.3.2:1080

#   # 是否在这个机器上自动配置nginx
#   autoSetupNginx: true

# 集群在HPC或是否启用，默认为true
hpc:
  enabled: true

# 集群在AI或是否启用，默认为false
ai:
  enabled: false
  # 开发及相关配置，可选
  # devHost:
  #   # 是否开启，默认为 false，可选
  #   enabled: false
  #   # vscode 相关配置，必填
  #   vscodeInfo:
  #     # vscode 二进制路径
  #     binPath: "/demo_path/vscode/bin/code-server"
  #   # 最大运行时间，可选，不填写表示不限制运行时间
  #   # maxRunningTimeHours: 10
  # 公共数据资产目录路径，若AI可用则必填，配置时需同步在集群中创建该目录, 该路径配置之后请勿随意修改，否则已有的公共数据资产将无法正常使用
  # clusterPublicPath: "/nfs/.public"

# # 可选，默认不开启
# storage:
#   # 必填，bool 类型
#   enabled: true
#   # 必填，字符串数组，代表当前需要被管理的文件系统挂载点
#   # 当前 SCOW 仅支持一个挂载点
#   paths: ["/data"]
#   # 可选，默认未开启副本备份
#   replicaExist: true

# 集群描述, 可选
# 此文本支持国际化
description: 集群描述

# 选配公共的挂载目录，优先级比ai/config.yaml中高
publicMountPoints:
  - /nfs/public

# 选配推理的配置，优先级比ai/config.yaml中高
inferConfig:
  # 选配，是否开启推理功能,默认开启
  # enabled: true
  # 推理服务代理地址，可选配置，不配置时用scow节点地址转发
  # proxyHost: www.example.com

# 选填作业监控配置，优先级比ai/config.yaml中高:注意grafana的 11.3.0 版本不支持单个面板的数据持续刷新, 11.2.2 版本的可以
jobMonitor:
  # 必填grafana模版中的 dashboardId 和 dashboardName
  dashboardId: P17D2FB9C9DA87D76
  dashboardName: p17d2fb9c9da87d76
  # 选填作业监控中要展示的panelId,有默认值(值如下所示)，每个字段对应一个面板 ID, 由grafana的规则决定
  panelIds:
    gpu: 4
    gpuMemory: 10
    cpu: 24
    memory: 26
    network: 46
