const tsNodeInterpreter = "node";
const tsNodeInterpreterArgs = ["-r ts-node/register", "-r tsconfig-paths/register", "--watch"].join(" ");

const PRODUCTION_ENV = {
  NODE_ENV: "production",
};

const SCOW_CONFIG_PATH_ENV = {
  SCOW_CONFIG_PATH: "../../dev/vagrant/config.local",
};

const PM2_INSTALL_CONFIG_PATH = "../../dev/vagrant/install.pm2.yaml";

const PM2_OPENAPI_INTERNAL_URL_ENV = {
  PORTAL_OPENAPI_INTERNAL_URL: "http://localhost:5001/api/openapi.json",
  MIS_OPENAPI_INTERNAL_URL: "http://localhost:5003/api/openapi.json",
  AI_OPENAPI_INTERNAL_URL: "http://localhost:5006/api/openapi.json",
  QUANTUM_OPENAPI_INTERNAL_URL: "http://localhost:5007/api/openapi.json",
  RESOURCE_OPENAPI_INTERNAL_URL: "http://localhost:6003/api/openapi.json",
  NOTIFICATION_OPENAPI_INTERNAL_URL: "http://localhost:6004/api/openapi.json",
};

module.exports = {
  apps: [
    {
      name: "auth",
      script: "src/index.ts",
      cwd: "./apps/auth",
      watch: ".",
      interpreter: "tsx",
      env: {
        PORT: "5000",
        AUTH_BASE_PATH: "/",
        ...PRODUCTION_ENV,
        ...SCOW_CONFIG_PATH_ENV,
      },
    },
    {
      name: "portal-web",
      script: "npm",
      args: "run dev:server",
      interpreter: "pnpm",
      cwd: "./apps/portal-web",
      env: {
        PORT: "5001",
        AUTH_EXTERNAL_URL: "http://localhost:5000",
        AUTH_INTERNAL_URL: "http://localhost:5000",
        NEXT_PUBLIC_USE_MOCK: 0,
        SERVER_URL: "localhost:5002",
        MIS_DEPLOYED: 1,
        MIS_URL: "localhost:5003",
        MIS_SERVER_URL: "localhost:5004",
        AUDIT_DEPLOYED: 1,
        AI_DEPLOYED: 1,
        AI_URL: "localhost:5006",
        NOVNC_CLIENT_URL: "http://localhost:6080",
        ...SCOW_CONFIG_PATH_ENV,
      },
    },
    {
      name: "portal-server",
      script: "src/index.ts",
      cwd: "./apps/portal-server",
      watch: ".",
      interpreter: "tsx",
      env: {
        PORT: "5002",
        MIS_DEPLOYED: 1,
        MIS_SERVER_URL: "localhost:5004",
        ...PRODUCTION_ENV,
        ...SCOW_CONFIG_PATH_ENV,
      },
    },
    {
      name: "mis-web",
      script: "npm",
      args: "run dev:server",
      cwd: "./apps/mis-web",
      interpreter: "pnpm",
      env: {
        PORT: "5003",
        AUTH_EXTERNAL_URL: "http://localhost:5000",
        AUTH_INTERNAL_URL: "http://localhost:5000",
        NEXT_PUBLIC_USE_MOCK: 0,
        SERVER_URL: "localhost:5004",
        PORTAL_DEPLOYED: 1,
        AUDIT_DEPLOYED: 1,
        PORTAL_URL: "localhost:5001",
        AI_DEPLOYED: 1,
        AI_URL: "localhost:5006",
        QUANTUM_DEPLOYED: 1,
        QUANTUM_URL: "localhost:5007",
        ...SCOW_CONFIG_PATH_ENV,
      },
    },
    {
      name: "mis-server",
      script: "src/index.ts",
      cwd: "./apps/mis-server",
      watch: ".",
      interpreter: tsNodeInterpreter,
      interpreter_args: tsNodeInterpreterArgs,
      env: {
        PORT: "5004",
        AUTH_URL: "http://localhost:5000",
        QUANTUM_URL: "localhost:5007",
        QUANTUM_DEPLOYED: 1,
        ...PRODUCTION_ENV,
        ...SCOW_CONFIG_PATH_ENV,
      },
    },
    {
      name: "audit-server",
      script: "src/index.ts",
      cwd: "./apps/audit-server",
      watch: ".",
      interpreter: tsNodeInterpreter,
      interpreter_args: tsNodeInterpreterArgs,
      env: {
        PORT: "5005",
        ...PRODUCTION_ENV,
        ...SCOW_CONFIG_PATH_ENV,
      },
    },
    {
      name: "ai",
      script: "npm",
      args: "run dev:server",
      cwd: "./apps/ai",
      interpreter: "pnpm",
      env: {
        PORT: "5006",
        AUTH_EXTERNAL_URL: "http://localhost:5000",
        AUTH_INTERNAL_URL: "http://localhost:5000",
        NEXT_PUBLIC_USE_MOCK: 0,
        SERVER_URL: "localhost:5004",
        PORTAL_DEPLOYED: 1,
        AUDIT_DEPLOYED: 1,
        PORTAL_URL: "localhost:5001",
        MIS_DEPLOYED: 1,
        MIS_URL: "localhost:5003",
        MIS_SERVER_URL: "localhost:5004",
        ...SCOW_CONFIG_PATH_ENV,
      },
    },
    {
      name: "quantum",
      script: "npm",
      args: "run dev:server",
      cwd: "./apps/quantum",
      interpreter: "pnpm",
      env: {
        PORT: "5007",
        AUTH_EXTERNAL_URL: "http://localhost:5000",
        AUTH_INTERNAL_URL: "http://localhost:5000",
        NEXT_PUBLIC_USE_MOCK: 0,
        SERVER_URL: "localhost:5004",
        PORTAL_DEPLOYED: 1,
        AUDIT_DEPLOYED: 1,
        PORTAL_URL: "localhost:5001",
        PORTAL_SERVER_URL: "localhost:5002",
        MIS_DEPLOYED: 1,
        MIS_URL: "localhost:5003",
        MIS_SERVER_URL: "localhost:5004",
        ...SCOW_CONFIG_PATH_ENV,
      },
    },
    {
      name: "resource",
      script: "npm",
      args: "run dev:server",
      interpreter: "pnpm",
      cwd: "./apps/resource",
      env: {
        PORT: "6003",
        AUTH_INTERNAL_URL: "http://localhost:5000",
        SERVER_URL: "http://localhost:6003",
        ...PRODUCTION_ENV,
        ...SCOW_CONFIG_PATH_ENV,
      },
    },
    {
      name: "notification",
      script: "npm",
      args: "run dev:server",
      interpreter: "pnpm",
      cwd: "./apps/notification",
      env: {
        PORT: "6004",
        AUTH_INTERNAL_URL: "http://localhost:5000",
        SERVER_URL: "http://localhost:6004",
        ...PRODUCTION_ENV,
        ...SCOW_CONFIG_PATH_ENV,
      },
    },
    {
      name: "meta-server",
      script: "src/index.ts",
      cwd: "./apps/meta-server",
      watch: ".",
      interpreter: "tsx",
      env: {
        PORT: "5010",
        INSTALL_CONFIG_PATH: PM2_INSTALL_CONFIG_PATH,
        SCOWCTL_BIN_DIR: "../scowctl/build/bin",
        ...PRODUCTION_ENV,
        ...PM2_OPENAPI_INTERNAL_URL_ENV,
      },
    },
    {
      name: "gateway",
      script: "src/devProxy.ts",
      cwd: "./apps/gateway",
      watch: ".",
      interpreter: "tsx",
      env: {
        PORT: "5080",
        BASE_PATH: "",
        PORTAL_ENABLED: "true",
        PORTAL_PATH: "/",
        PORTAL_PATH_INTERNAL_URL: "http://localhost:5001",
        MIS_ENABLED: "true",
        MIS_PATH: "/mis",
        MIS_PATH_INTERNAL_URL: "http://localhost:5003",
        AI_ENABLED: "true",
        AI_PATH: "/ai",
        AI_PATH_INTERNAL_URL: "http://localhost:5006",
        QUANTUM_ENABLED: "true",
        QUANTUM_PATH: "/quantum",
        QUANTUM_PATH_INTERNAL_URL: "http://localhost:5007",
        RESOURCE_PATH: "/resource",
        RESOURCE_PATH_INTERNAL_URL: "http://localhost:6003",
        NOTIFICATION_PATH: "/notification",
        NOTIFICATION_PATH_INTERNAL_URL: "http://localhost:6004",
        VNC_ENABLED: "false",
        AUTH_URL: "http://localhost:5000",
        META_SERVER_URL: "http://localhost:5010",
        ...PRODUCTION_ENV,
      },
    },
    {
      name: "dev:libs",
      cwd: ".",
      script: "npm",
      args: "run dev:libs",
      interpreter: "pnpm",
    },
  ],
};
