/* eslint-disable */
// AUTO-GENERATED by scripts/generate-openapi-registry.mjs — do not edit manually
// Re-run after: npm run client

import { ConfirmAccountStorageQuotaSchema } from "src/pages/api/admin/accountStorageQuota/confirm";
import { EnableAccountStorageQuotaSchema } from "src/pages/api/admin/accountStorageQuota/enable";
import { GetAccountStorageQuotaStateSchema } from "src/pages/api/admin/accountStorageQuota/getState";
import { ActivateClusterSchema } from "src/pages/api/admin/activateCluster";
import { ActivateNodeSchema } from "src/pages/api/admin/activateNode";
import { AuthorizeAppSchema } from "src/pages/api/admin/authorization/authorizeApp";
import { GetTargetAppAuthorizationsSchema } from "src/pages/api/admin/authorization/getTargetAppAuthorizations";
import { ChangeJobPriceSchema } from "src/pages/api/admin/changeJobPrice";
import { ChangePasswordAsPlatformAdminSchema } from "src/pages/api/admin/changePassword";
import { DeactivateClusterSchema } from "src/pages/api/admin/deactivateCluster";
import { EditUserProfileSchema } from "src/pages/api/admin/editUserProfile";
import { FetchJobsSchema } from "src/pages/api/admin/fetchJobs/fetchJobs";
import { GetFetchJobInfoSchema } from "src/pages/api/admin/fetchJobs/getFetchInfo";
import { SetFetchStateSchema } from "src/pages/api/admin/fetchJobs/setFetchState";
import { TenantFinancePaySchema } from "src/pages/api/admin/finance/pay";
import { GetTenantPaymentsSchema } from "src/pages/api/admin/finance/payments";
import { GetAccountGroupStatusSchema } from "src/pages/api/admin/getAccountGroupStatus";
import { GetActiveUserCountSchema } from "src/pages/api/admin/getActiveUserCount";
import { GetAllAccountsSchema } from "src/pages/api/admin/getAllAccounts";
import { GetAllTenantsSchema } from "src/pages/api/admin/getAllTenants";
import { GetAllUsersSchema } from "src/pages/api/admin/getAllUsers";
import { GetClusterMigrateNodesInfoSchema } from "src/pages/api/admin/getClusterMigrateNodesInfo";
import { GetClusterUsersSchema } from "src/pages/api/admin/getClusterUsers";
import { GetClustersConnectionInfoSchema } from "src/pages/api/admin/getClustersConnectionInfo";
import { GetClustersRuntimeInfoSchema } from "src/pages/api/admin/getClustersRuntimeInfo";
import { GetDailyChargeSchema } from "src/pages/api/admin/getDailyCharge";
import { GetDailyPaySchema } from "src/pages/api/admin/getDailyPay";
import { GetJobTotalCountSchema } from "src/pages/api/admin/getJobTotalCount";
import { GetLockedUsersSchema } from "src/pages/api/admin/getLockedUsers";
import { GetMisUsageCountSchema } from "src/pages/api/admin/getMisUsageCount";
import { GetNewJobCountSchema } from "src/pages/api/admin/getNewJobCount";
import { GetNewUserCountSchema } from "src/pages/api/admin/getNewUserCount";
import { GetPlatformUsersCountsSchema } from "src/pages/api/admin/getPlatformUsersCounts";
import { GetPortalUsageCountSchema } from "src/pages/api/admin/getPortalUsageCount";
import { GetStatisticInfoSchema } from "src/pages/api/admin/getStatisticInfo";
import { GetTenantUsersSchema } from "src/pages/api/admin/getTenantUsers";
import { GetTopChargeAccountSchema } from "src/pages/api/admin/getTopChargeAccount";
import { GetTopPayAccountSchema } from "src/pages/api/admin/getTopPayAccount";
import { GetTopSubmitJobUserSchema } from "src/pages/api/admin/getTopSubmitJobUser";
import { GetUsersWithMostJobSubmissionsSchema } from "src/pages/api/admin/getUsersWithMostJobSubmissions";
import { ImportUsersSchema } from "src/pages/api/admin/importUsers";
import { InitAccountGroupSchema } from "src/pages/api/admin/initAccountGroup";
import { AccountThresholdSchema } from "src/pages/api/admin/isAccountBelowBlockThreshold";
import { MigrateNodeSchema } from "src/pages/api/admin/migrateNode";
import { GetAlarmDbIdSchema } from "src/pages/api/admin/monitor/getAlarmDbId";
import { GetAlarmLogsSchema } from "src/pages/api/admin/monitor/getAlarmLogs";
import { GetAlarmLogsCountSchema } from "src/pages/api/admin/monitor/getAlarmLogsCount";
import { SetAccountGroupInitConfirmedSchema } from "src/pages/api/admin/setAccountGroupInitConfirmed";
import { SetPlatformRoleSchema } from "src/pages/api/admin/setPlatformRole";
import { SetTenantRoleSchema } from "src/pages/api/admin/setTenantRole";
import { GetSyncAccountUserHistorySchema } from "src/pages/api/admin/synchronize/getSyncAccountUserHistory";
import { GetSyncBlockStatusJobInfoSchema } from "src/pages/api/admin/synchronize/getSyncBlockStateInfo";
import { SetSyncBlockStatusStateSchema } from "src/pages/api/admin/synchronize/setSynchronizeState";
import { SyncAccountUserInfoSchema } from "src/pages/api/admin/synchronize/syncAccountUserInfo";
import { SyncBlockStatusSchema } from "src/pages/api/admin/synchronize/syncBlockStatus";
import { UnlockUserSchema } from "src/pages/api/admin/unlockUser";
import { UnsetPlatformRoleSchema } from "src/pages/api/admin/unsetPlatformRole";
import { UnsetTenantRoleSchema } from "src/pages/api/admin/unsetTenantRole";
import { UpdatePasswordResetFlagSchema } from "src/pages/api/admin/updatePasswordResetFlag";
import { AuthCallbackSchema } from "src/pages/api/auth/callback";
import { LogoutSchema } from "src/pages/api/auth/logout";
import { ValidateTokenSchema } from "src/pages/api/auth/validateToken";
import { GetAccountsAssociatedClustersSchema } from "src/pages/api/cluster/getAccountsAssociatedClusters";
import { GetUserAssociatedClustersSchema } from "src/pages/api/cluster/getUserAssociatedClusters";
import { GetClusterConfigFilesSchema } from "src/pages/api//clusterConfigsInfo";
import { GetUserStatusSchema } from "src/pages/api/dashboard/status";
import { ExportAccountSchema } from "src/pages/api/file/exportAccount";
import { ExportBillSchema } from "src/pages/api/file/exportBill";
import { ExportChargeRecordSchema } from "src/pages/api/file/exportChargeRecord";
import { ExportJobRecordSchema } from "src/pages/api/file/exportJobRecord";
import { ExportOperationLogSchema } from "src/pages/api/file/exportOperationLog";
import { ExportPayRecordSchema } from "src/pages/api/file/exportPayRecord";
import { ExportUserSchema } from "src/pages/api/file/exportUser";
import { exportUserBillSchema } from "src/pages/api/file/exportUserBill";
import { GetBillsSchema } from "src/pages/api/finance/bill";
import { GetBillTypesSchema } from "src/pages/api/finance/billTypes";
import { GetChargesSchema } from "src/pages/api/finance/charges";
import { GetChargeRecordsTotalCountSchema } from "src/pages/api/finance/getChargeRecordsTotalCount";
import { GetUsedPayTypesSchema } from "src/pages/api/finance/getUsedPayTypes";
import { FinancePaySchema } from "src/pages/api/finance/pay";
import { GetPaymentsSchema } from "src/pages/api/finance/payments";
import { GetUserBillsSchema } from "src/pages/api/finance/userBill";
import { GetAppInitialConfigSchema } from "src/pages/api//getAppInitialConfig";
import { GetClusterConfigSchema } from "src/pages/api//getClusterConfig";
import { CompleteInitSchema } from "src/pages/api/init/completeInit";
import { CreateInitAdminSchema } from "src/pages/api/init/createInitAdmin";
import { InitGetAccountsSchema } from "src/pages/api/init/getAccounts";
import { InitGetUsersSchema } from "src/pages/api/init/getUsers";
import { SetAsInitAdminSchema } from "src/pages/api/init/setAsInitAdmin";
import { UnsetInitAdminSchema } from "src/pages/api/init/unsetInitAdmin";
import { UserExistsSchema } from "src/pages/api/init/userExists";
import { AddBillingItemSchema } from "src/pages/api/job/addBillingItem";
import { CancelJobSchema } from "src/pages/api/job/cancelJob";
import { ChangeJobTimeLimitSchema } from "src/pages/api/job/changeJobTimeLimit";
import { GetAvailableBillingTableSchema } from "src/pages/api/job/getAvailableBillingTable";
import { GetBillingItemsSchema } from "src/pages/api/job/getBillingItems";
import { GetJobByBiJobIndexSchema } from "src/pages/api/job/getJobByBiJobIndex";
import { GetMissingDefaultPriceItemsSchema } from "src/pages/api/job/getMissingDefaultPriceItems";
import { GetJobInfoSchema } from "src/pages/api/job/jobInfo";
import { QueryJobTimeLimitSchema } from "src/pages/api/job/queryJobTimeLimit";
import { GetRunningJobsSchema } from "src/pages/api/job/runningJobs";
import { GetCustomEventTypesSchema } from "src/pages/api/log/getCustomEventTypes";
import { GetOperationLogsSchema } from "src/pages/api/log/getOperationLog";
import { GetUnreadMessagesSchema } from "src/pages/api/notification/getUnreadMessages";
import { MarkMessageReadSchema } from "src/pages/api/notification/markMessageRead";
import { ChangeEmailSchema } from "src/pages/api/profile/changeEmail";
import { ChangePasswordSchema } from "src/pages/api/profile/changePassword";
import { CheckPasswordSchema } from "src/pages/api/profile/checkPassword";
import { GetQuantumJobInfoSchema } from "src/pages/api/quantum/jobInfo";
import { GetSimpleClustersInfoFromConfigFilesSchema } from "src/pages/api//simpleClustersInfo";
import { BatchSetTenantUsersQuotaSchema } from "src/pages/api/storage/batchSetTenantUsersQuota";
import { GetAccountStorageSyncInfoSchema } from "src/pages/api/storage/getAccountStorageSyncInfo";
import { GetStorageSyncInfoSchema } from "src/pages/api/storage/getStorageSyncInfo";
import { GetTenantQuotaSchema } from "src/pages/api/storage/getTenantQuota";
import { GetTenantQuotaSummarySchema } from "src/pages/api/storage/getTenantQuotaSummary";
import { SetTenantUserDefaultQuotaSchema } from "src/pages/api/storage/setTenantUserDefaultQuota";
import { SetTenantUserQuotaSchema } from "src/pages/api/storage/setTenantUserQuota";
import { SyncTenantAccountsStorageUsageSchema } from "src/pages/api/storage/syncTenantAccountsStorageUsage";
import { SyncTenantUsersStorageUsageSchema } from "src/pages/api/storage/syncTenantUsersStorageUsage";
import { AddStorageBillingItemSchema } from "src/pages/api/storageBilling/addStorageBillingItem";
import { GetStorageBillingItemsSchema } from "src/pages/api/storageBilling/getStorageBillingItems";
import { BatchSetAccountQuotaSchema } from "src/pages/api/tenant/accountStorageQuota/batchSetAccountQuota";
import { GetAccountQuotaSchema } from "src/pages/api/tenant/accountStorageQuota/getAccountQuota";
import { SetAccountDefaultQuotaSchema } from "src/pages/api/tenant/accountStorageQuota/setAccountDefaultQuota";
import { DewhitelistAccountSchema } from "src/pages/api/tenant/accountWhitelist/dewhitelistAccount";
import { GetWhitelistedAccountsSchema } from "src/pages/api/tenant/accountWhitelist/getWhitelistedAccounts";
import { WhitelistAccountSchema } from "src/pages/api/tenant/accountWhitelist/whitelistAccount";
import { GetTenantAppsSchema } from "src/pages/api/tenant/authorization/getTenantApps";
import { UpdateDefaultAppSchema } from "src/pages/api/tenant/authorization/updateDefaultApp";
import { BlockAccountSchema } from "src/pages/api/tenant/blockAccount";
import { ChangePasswordAsTenantAdminSchema } from "src/pages/api/tenant/changePassword";
import { CreateTenantSchema } from "src/pages/api/tenant/create";
import { CreateAccountSchema } from "src/pages/api/tenant/createAccount";
import { CreateTenantWithExistingUserAsAdminSchema } from "src/pages/api/tenant/createTenantWithExistingUserAsAdmin";
import { DeleteAccountSchema } from "src/pages/api/tenant/deleteAccount";
import { GetAccountsSchema } from "src/pages/api/tenant/getAccounts";
import { GetTenantAssignedClustersAndPartitionsSchema } from "src/pages/api/tenant/getTenantAssignedClustersAndPartitions";
import { GetTenantsSchema } from "src/pages/api/tenant/getTenants";
import { SetBlockThresholdSchema } from "src/pages/api/tenant/setBlockThreshold";
import { SetDefaultAccountBlockThresholdSchema } from "src/pages/api/tenant/setDefaultAccountBlockThreshold";
import { UnblockAccountSchema } from "src/pages/api/tenant/unblockAccount";
import { AddUserToAccountSchema } from "src/pages/api/users/addToAccount";
import { BlockUserInAccountSchema } from "src/pages/api/users/blockInAccount";
import { ChangeTenantSchema } from "src/pages/api/users/changeTenant";
import { CreateUserSchema } from "src/pages/api/users/create";
import { DeleteUserSchema } from "src/pages/api/users/delete";
import { GetAccountUsersSchema } from "src/pages/api/users/index";
import { CancelJobChargeLimitSchema } from "src/pages/api/users/jobChargeLimit/cancel";
import { SetJobChargeLimitSchema } from "src/pages/api/users/jobChargeLimit/set";
import { RemoveUserFromAccountSchema } from "src/pages/api/users/removeFromAccount";
import { SetAdminSchema } from "src/pages/api/users/setAsAdmin";
import { UnblockUserInAccountSchema } from "src/pages/api/users/unblockInAccount";
import { UnsetAdminSchema } from "src/pages/api/users/unsetAdmin";

import type { RouteEntry } from "@scow/lib-web/build/utils/typebox-to-openapi";

export const openapiRoutes: RouteEntry[] = [
  { schema: ConfirmAccountStorageQuotaSchema, method: "POST", url: "/api/admin/accountStorageQuota/confirm" },
  { schema: EnableAccountStorageQuotaSchema, method: "POST", url: "/api/admin/accountStorageQuota/enable" },
  { schema: GetAccountStorageQuotaStateSchema, method: "GET", url: "/api/admin/accountStorageQuota/getState" },
  { schema: ActivateClusterSchema, method: "PUT", url: "/api/admin/activateCluster" },
  { schema: ActivateNodeSchema, method: "PATCH", url: "/api/admin/activateNode" },
  { schema: AuthorizeAppSchema, method: "PUT", url: "/api/admin/authorization/authorizeApp" },
  { schema: GetTargetAppAuthorizationsSchema, method: "GET", url: "/api/admin/authorization/getTargetAppAuthorizations" },
  { schema: ChangeJobPriceSchema, method: "PATCH", url: "/api/admin/changeJobPrice" },
  { schema: ChangePasswordAsPlatformAdminSchema, method: "PATCH", url: "/api/admin/changePassword" },
  { schema: DeactivateClusterSchema, method: "PUT", url: "/api/admin/deactivateCluster" },
  { schema: EditUserProfileSchema, method: "PATCH", url: "/api/admin/editUserProfile" },
  { schema: FetchJobsSchema, method: "POST", url: "/api/admin/fetchJobs/fetchJobs" },
  { schema: GetFetchJobInfoSchema, method: "GET", url: "/api/admin/fetchJobs/getFetchInfo" },
  { schema: SetFetchStateSchema, method: "POST", url: "/api/admin/fetchJobs/setFetchState" },
  { schema: TenantFinancePaySchema, method: "POST", url: "/api/admin/finance/pay" },
  { schema: GetTenantPaymentsSchema, method: "GET", url: "/api/admin/finance/payments" },
  { schema: GetAccountGroupStatusSchema, method: "GET", url: "/api/admin/getAccountGroupStatus" },
  { schema: GetActiveUserCountSchema, method: "GET", url: "/api/admin/getActiveUserCount" },
  { schema: GetAllAccountsSchema, method: "GET", url: "/api/admin/getAllAccounts" },
  { schema: GetAllTenantsSchema, method: "GET", url: "/api/admin/getAllTenants" },
  { schema: GetAllUsersSchema, method: "GET", url: "/api/admin/getAllUsers" },
  { schema: GetClusterMigrateNodesInfoSchema, method: "GET", url: "/api/admin/getClusterMigrateNodesInfo" },
  { schema: GetClusterUsersSchema, method: "GET", url: "/api/admin/getClusterUsers" },
  { schema: GetClustersConnectionInfoSchema, method: "GET", url: "/api/admin/getClustersConnectionInfo" },
  { schema: GetClustersRuntimeInfoSchema, method: "GET", url: "/api/admin/getClustersRuntimeInfo" },
  { schema: GetDailyChargeSchema, method: "GET", url: "/api/admin/getDailyCharge" },
  { schema: GetDailyPaySchema, method: "GET", url: "/api/admin/getDailyPay" },
  { schema: GetJobTotalCountSchema, method: "GET", url: "/api/admin/getJobTotalCount" },
  { schema: GetLockedUsersSchema, method: "GET", url: "/api/admin/getLockedUsers" },
  { schema: GetMisUsageCountSchema, method: "GET", url: "/api/admin/getMisUsageCount" },
  { schema: GetNewJobCountSchema, method: "GET", url: "/api/admin/getNewJobCount" },
  { schema: GetNewUserCountSchema, method: "GET", url: "/api/admin/getNewUserCount" },
  { schema: GetPlatformUsersCountsSchema, method: "GET", url: "/api/admin/getPlatformUsersCounts" },
  { schema: GetPortalUsageCountSchema, method: "GET", url: "/api/admin/getPortalUsageCount" },
  { schema: GetStatisticInfoSchema, method: "GET", url: "/api/admin/getStatisticInfo" },
  { schema: GetTenantUsersSchema, method: "GET", url: "/api/admin/getTenantUsers" },
  { schema: GetTopChargeAccountSchema, method: "GET", url: "/api/admin/getTopChargeAccount" },
  { schema: GetTopPayAccountSchema, method: "GET", url: "/api/admin/getTopPayAccount" },
  { schema: GetTopSubmitJobUserSchema, method: "GET", url: "/api/admin/getTopSubmitJobUser" },
  { schema: GetUsersWithMostJobSubmissionsSchema, method: "GET", url: "/api/admin/getUsersWithMostJobSubmissions" },
  { schema: ImportUsersSchema, method: "POST", url: "/api/admin/importUsers" },
  { schema: InitAccountGroupSchema, method: "POST", url: "/api/admin/initAccountGroup" },
  { schema: AccountThresholdSchema, method: "GET", url: "/api/admin/isAccountBelowBlockThreshold" },
  { schema: MigrateNodeSchema, method: "PATCH", url: "/api/admin/migrateNode" },
  { schema: GetAlarmDbIdSchema, method: "GET", url: "/api/admin/monitor/getAlarmDbId" },
  { schema: GetAlarmLogsSchema, method: "GET", url: "/api/admin/monitor/getAlarmLogs" },
  { schema: GetAlarmLogsCountSchema, method: "GET", url: "/api/admin/monitor/getAlarmLogsCount" },
  { schema: SetAccountGroupInitConfirmedSchema, method: "POST", url: "/api/admin/setAccountGroupInitConfirmed" },
  { schema: SetPlatformRoleSchema, method: "PUT", url: "/api/admin/setPlatformRole" },
  { schema: SetTenantRoleSchema, method: "PUT", url: "/api/admin/setTenantRole" },
  { schema: GetSyncAccountUserHistorySchema, method: "GET", url: "/api/admin/synchronize/getSyncAccountUserHistory" },
  { schema: GetSyncBlockStatusJobInfoSchema, method: "GET", url: "/api/admin/synchronize/getSyncBlockStateInfo" },
  { schema: SetSyncBlockStatusStateSchema, method: "POST", url: "/api/admin/synchronize/setSynchronizeState" },
  { schema: SyncAccountUserInfoSchema, method: "PUT", url: "/api/admin/synchronize/syncAccountUserInfo" },
  { schema: SyncBlockStatusSchema, method: "PUT", url: "/api/admin/synchronize/syncBlockStatus" },
  { schema: UnlockUserSchema, method: "PATCH", url: "/api/admin/unlockUser" },
  { schema: UnsetPlatformRoleSchema, method: "PUT", url: "/api/admin/unsetPlatformRole" },
  { schema: UnsetTenantRoleSchema, method: "PUT", url: "/api/admin/unsetTenantRole" },
  { schema: UpdatePasswordResetFlagSchema, method: "PATCH", url: "/api/admin/updatePasswordResetFlag" },
  { schema: AuthCallbackSchema, method: "GET", url: "/api/auth/callback" },
  { schema: LogoutSchema, method: "DELETE", url: "/api/auth/logout" },
  { schema: ValidateTokenSchema, method: "GET", url: "/api/auth/validateToken" },
  { schema: GetAccountsAssociatedClustersSchema, method: "GET", url: "/api/cluster/getAccountsAssociatedClusters" },
  { schema: GetUserAssociatedClustersSchema, method: "GET", url: "/api/cluster/getUserAssociatedClusters" },
  { schema: GetClusterConfigFilesSchema, method: "GET", url: "/api//clusterConfigsInfo" },
  { schema: GetUserStatusSchema, method: "GET", url: "/api/dashboard/status" },
  { schema: ExportAccountSchema, method: "GET", url: "/api/file/exportAccount" },
  { schema: ExportBillSchema, method: "GET", url: "/api/file/exportBill" },
  { schema: ExportChargeRecordSchema, method: "GET", url: "/api/file/exportChargeRecord" },
  { schema: ExportJobRecordSchema, method: "GET", url: "/api/file/exportJobRecord" },
  { schema: ExportOperationLogSchema, method: "GET", url: "/api/file/exportOperationLog" },
  { schema: ExportPayRecordSchema, method: "GET", url: "/api/file/exportPayRecord" },
  { schema: ExportUserSchema, method: "GET", url: "/api/file/exportUser" },
  { schema: exportUserBillSchema, method: "GET", url: "/api/file/exportUserBill" },
  { schema: GetBillsSchema, method: "GET", url: "/api/finance/bill" },
  { schema: GetBillTypesSchema, method: "GET", url: "/api/finance/billTypes" },
  { schema: GetChargesSchema, method: "GET", url: "/api/finance/charges" },
  { schema: GetChargeRecordsTotalCountSchema, method: "GET", url: "/api/finance/getChargeRecordsTotalCount" },
  { schema: GetUsedPayTypesSchema, method: "GET", url: "/api/finance/getUsedPayTypes" },
  { schema: FinancePaySchema, method: "POST", url: "/api/finance/pay" },
  { schema: GetPaymentsSchema, method: "GET", url: "/api/finance/payments" },
  { schema: GetUserBillsSchema, method: "GET", url: "/api/finance/userBill" },
  { schema: GetAppInitialConfigSchema, method: "GET", url: "/api//getAppInitialConfig" },
  { schema: GetClusterConfigSchema, method: "GET", url: "/api//getClusterConfig" },
  { schema: CompleteInitSchema, method: "POST", url: "/api/init/completeInit" },
  { schema: CreateInitAdminSchema, method: "POST", url: "/api/init/createInitAdmin" },
  { schema: InitGetAccountsSchema, method: "GET", url: "/api/init/getAccounts" },
  { schema: InitGetUsersSchema, method: "GET", url: "/api/init/getUsers" },
  { schema: SetAsInitAdminSchema, method: "PATCH", url: "/api/init/setAsInitAdmin" },
  { schema: UnsetInitAdminSchema, method: "DELETE", url: "/api/init/unsetInitAdmin" },
  { schema: UserExistsSchema, method: "POST", url: "/api/init/userExists" },
  { schema: AddBillingItemSchema, method: "POST", url: "/api/job/addBillingItem" },
  { schema: CancelJobSchema, method: "DELETE", url: "/api/job/cancelJob" },
  { schema: ChangeJobTimeLimitSchema, method: "PATCH", url: "/api/job/changeJobTimeLimit" },
  { schema: GetAvailableBillingTableSchema, method: "GET", url: "/api/job/getAvailableBillingTable" },
  { schema: GetBillingItemsSchema, method: "GET", url: "/api/job/getBillingItems" },
  { schema: GetJobByBiJobIndexSchema, method: "GET", url: "/api/job/getJobByBiJobIndex" },
  { schema: GetMissingDefaultPriceItemsSchema, method: "GET", url: "/api/job/getMissingDefaultPriceItems" },
  { schema: GetJobInfoSchema, method: "GET", url: "/api/job/jobInfo" },
  { schema: QueryJobTimeLimitSchema, method: "GET", url: "/api/job/queryJobTimeLimit" },
  { schema: GetRunningJobsSchema, method: "GET", url: "/api/job/runningJobs" },
  { schema: GetCustomEventTypesSchema, method: "GET", url: "/api/log/getCustomEventTypes" },
  { schema: GetOperationLogsSchema, method: "GET", url: "/api/log/getOperationLog" },
  { schema: GetUnreadMessagesSchema, method: "GET", url: "/api/notification/getUnreadMessages" },
  { schema: MarkMessageReadSchema, method: "POST", url: "/api/notification/markMessageRead" },
  { schema: ChangeEmailSchema, method: "PATCH", url: "/api/profile/changeEmail" },
  { schema: ChangePasswordSchema, method: "PATCH", url: "/api/profile/changePassword" },
  { schema: CheckPasswordSchema, method: "GET", url: "/api/profile/checkPassword" },
  { schema: GetQuantumJobInfoSchema, method: "GET", url: "/api/quantum/jobInfo" },
  { schema: GetSimpleClustersInfoFromConfigFilesSchema, method: "GET", url: "/api//simpleClustersInfo" },
  { schema: BatchSetTenantUsersQuotaSchema, method: "PUT", url: "/api/storage/batchSetTenantUsersQuota" },
  { schema: GetAccountStorageSyncInfoSchema, method: "GET", url: "/api/storage/getAccountStorageSyncInfo" },
  { schema: GetStorageSyncInfoSchema, method: "GET", url: "/api/storage/getStorageSyncInfo" },
  { schema: GetTenantQuotaSchema, method: "GET", url: "/api/storage/getTenantQuota" },
  { schema: GetTenantQuotaSummarySchema, method: "GET", url: "/api/storage/getTenantQuotaSummary" },
  { schema: SetTenantUserDefaultQuotaSchema, method: "PUT", url: "/api/storage/setTenantUserDefaultQuota" },
  { schema: SetTenantUserQuotaSchema, method: "PUT", url: "/api/storage/setTenantUserQuota" },
  { schema: SyncTenantAccountsStorageUsageSchema, method: "POST", url: "/api/storage/syncTenantAccountsStorageUsage" },
  { schema: SyncTenantUsersStorageUsageSchema, method: "POST", url: "/api/storage/syncTenantUsersStorageUsage" },
  { schema: AddStorageBillingItemSchema, method: "POST", url: "/api/storageBilling/addStorageBillingItem" },
  { schema: GetStorageBillingItemsSchema, method: "GET", url: "/api/storageBilling/getStorageBillingItems" },
  { schema: BatchSetAccountQuotaSchema, method: "PUT", url: "/api/tenant/accountStorageQuota/batchSetAccountQuota" },
  { schema: GetAccountQuotaSchema, method: "GET", url: "/api/tenant/accountStorageQuota/getAccountQuota" },
  { schema: SetAccountDefaultQuotaSchema, method: "PUT", url: "/api/tenant/accountStorageQuota/setAccountDefaultQuota" },
  { schema: DewhitelistAccountSchema, method: "DELETE", url: "/api/tenant/accountWhitelist/dewhitelistAccount" },
  { schema: GetWhitelistedAccountsSchema, method: "GET", url: "/api/tenant/accountWhitelist/getWhitelistedAccounts" },
  { schema: WhitelistAccountSchema, method: "PUT", url: "/api/tenant/accountWhitelist/whitelistAccount" },
  { schema: GetTenantAppsSchema, method: "GET", url: "/api/tenant/authorization/getTenantApps" },
  { schema: UpdateDefaultAppSchema, method: "PUT", url: "/api/tenant/authorization/updateDefaultApp" },
  { schema: BlockAccountSchema, method: "PUT", url: "/api/tenant/blockAccount" },
  { schema: ChangePasswordAsTenantAdminSchema, method: "PATCH", url: "/api/tenant/changePassword" },
  { schema: CreateTenantSchema, method: "POST", url: "/api/tenant/create" },
  { schema: CreateAccountSchema, method: "POST", url: "/api/tenant/createAccount" },
  { schema: CreateTenantWithExistingUserAsAdminSchema, method: "POST", url: "/api/tenant/createTenantWithExistingUserAsAdmin" },
  { schema: DeleteAccountSchema, method: "DELETE", url: "/api/tenant/deleteAccount" },
  { schema: GetAccountsSchema, method: "GET", url: "/api/tenant/getAccounts" },
  { schema: GetTenantAssignedClustersAndPartitionsSchema, method: "GET", url: "/api/tenant/getTenantAssignedClustersAndPartitions" },
  { schema: GetTenantsSchema, method: "GET", url: "/api/tenant/getTenants" },
  { schema: SetBlockThresholdSchema, method: "PUT", url: "/api/tenant/setBlockThreshold" },
  { schema: SetDefaultAccountBlockThresholdSchema, method: "PUT", url: "/api/tenant/setDefaultAccountBlockThreshold" },
  { schema: UnblockAccountSchema, method: "PUT", url: "/api/tenant/unblockAccount" },
  { schema: AddUserToAccountSchema, method: "POST", url: "/api/users/addToAccount" },
  { schema: BlockUserInAccountSchema, method: "PUT", url: "/api/users/blockInAccount" },
  { schema: ChangeTenantSchema, method: "PUT", url: "/api/users/changeTenant" },
  { schema: CreateUserSchema, method: "POST", url: "/api/users/create" },
  { schema: DeleteUserSchema, method: "DELETE", url: "/api/users/delete" },
  { schema: GetAccountUsersSchema, method: "GET", url: "/api/users" },
  { schema: CancelJobChargeLimitSchema, method: "DELETE", url: "/api/users/jobChargeLimit/cancel" },
  { schema: SetJobChargeLimitSchema, method: "PUT", url: "/api/users/jobChargeLimit/set" },
  { schema: RemoveUserFromAccountSchema, method: "DELETE", url: "/api/users/removeFromAccount" },
  { schema: SetAdminSchema, method: "PUT", url: "/api/users/setAsAdmin" },
  { schema: UnblockUserInAccountSchema, method: "PUT", url: "/api/users/unblockInAccount" },
  { schema: UnsetAdminSchema, method: "PUT", url: "/api/users/unsetAdmin" },
];
